service: authorization

frameworkVersion: '2'

useDotenv: true

plugins:
  - serverless-rollup-plugin

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  environment:
    vladshcherbin: ${env:vladshcherbin}

functions:
  basicAuthorizer:
    handler: src/handlers/basic-authorizer.handler

custom:
  rollup:
    config: ./rollup.config.js
    installCommand: yarn add
    dependencies:
      - pino
