service: product

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  getProductsList:
    handler: handler.productsList
    events:
      - http:
          path: products
          method: get
