service: products

frameworkVersion: '2'

useDotenv: true

plugins:
  - serverless-lift
  - serverless-rollup-plugin

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_DATABASE: ${env:DB_DATABASE}

constructs:
  catalog-items-queue:
    type: queue
    worker:
      handler: src/handlers/catalog-batch-process.handler
    batchSize: 5

functions:
  migration:
    handler: src/handlers/migration.handler
    copyFiles:
      - migrations
  productsList:
    handler: src/handlers/products-list.handler
    events:
      - http:
          path: products
          method: get
          cors: true
  productById:
    handler: src/handlers/product-by-id.handler
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  createProduct:
    handler: src/handlers/create-product.handler
    dependencies:
      - yup
    events:
      - http:
          path: products/create
          method: post
          cors: true

resources:
  Outputs:
    CatalogItemsQueueArn:
      Value: ${construct:catalog-items-queue.queueArn}
    CatalogItemsQueueUrl:
      Value: ${construct:catalog-items-queue.queueUrl}

custom:
  rollup:
    config: ./rollup.config.js
    installCommand: yarn add
    dependencies:
      - knex
      - pg
      - pino
