service: products

frameworkVersion: '2'

plugins:
  - serverless-rollup-plugin

package:
  individually: true

custom:
  rollup:
    config: ./rollup.config.js
    installCommand: yarn add

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  getProductsList:
    handler: src/handler.productsList
    events:
      - http:
          path: products
          method: get
