service: products

frameworkVersion: '2'

plugins:
  - serverless-rollup-plugin

package:
  individually: true

custom:
  rollup:
    config: ./rollup.config.js
    installCommand: yarn add

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  productsList:
    handler: src/handlers/products-list.handler
    events:
      - http:
          path: products
          method: get
          cors: true
  productBySlug:
    handler: src/handlers/product-by-slug.handler
    events:
      - http:
          path: products/{slug}
          method: get
          cors: true
          request:
            parameters:
              paths:
                slug: true
