service: import

frameworkVersion: '2'

useDotenv: true

plugins:
  - serverless-rollup-plugin

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:CopyObject'
            - 's3:DeleteObject'
            - 's3:GetObject'
            - 's3:PutObject'
          Resource: 'arn:aws:s3:::${env:BUCKET_NAME}/*'
        - Effect: Allow
          Action:
            - 'sqs:SendMessage'
          Resource: ${cf:products-${sls:stage}.CatalogItemsQueueArn}

functions:
  importFileParser:
    handler: src/handlers/import-file-parser.handler
    events:
      - s3:
          bucket: ${env:BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true
    dependencies:
      - '@aws-sdk/client-sqs'
      - csv-parser
    environment:
      QUEUE_URL: ${cf:products-${sls:stage}.CatalogItemsQueueUrl}
  importProductsFile:
    handler: src/handlers/import-products-file.handler
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
    dependencies:
      - '@aws-sdk/s3-request-presigner'

custom:
  rollup:
    config: ./rollup.config.js
    installCommand: yarn add
    dependencies:
      - '@aws-sdk/client-s3'
      - pino
