service: import

frameworkVersion: '2'

useDotenv: true

plugins:
  - serverless-rollup-plugin

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:PutObject'
          Resource: 'arn:aws:s3:::${env:BUCKET_NAME}/*'

functions:
  importProductsFile:
    handler: src/handlers/import-products-file.handler
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
    dependencies:
      - '@aws-sdk/client-s3'
      - '@aws-sdk/s3-request-presigner'
      - pino

custom:
  rollup:
    config: ./rollup.config.js
    installCommand: yarn add
